---
services:
  broker:
    image: confluentinc/cp-kafka:8.0.0
    hostname: broker
    container_name: broker
    networks:
      - spring-boot-kafka-quickstarts
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  control-center:
    image: confluentinc/cp-enterprise-control-center-next-gen:2.2.2
    hostname: control-center
    container_name: control-center
    networks:
      - spring-boot-kafka-quickstarts
    depends_on:
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_MODE_ENABLE: "management"
      PORT: 9021

  kafka-producer-simple:
    image: loicgreffier/spring-boot-kafka-quickstarts:kafka-producer-simple-1.0.0
    hostname: kafka-producer-simple
    container_name: kafka-producer-simple
    networks:
      - spring-boot-kafka-quickstarts
    depends_on:
      - broker
    ports:
      - "8082:8080"
    restart: unless-stopped
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "kafka": {
            "properties": {
              "bootstrap.servers": "broker:29092"
            }
          }
        }

  kafka-consumer-simple:
    image: loicgreffier/spring-boot-kafka-quickstarts:kafka-consumer-simple-1.0.0
    hostname: kafka-consumer-simple
    container_name: kafka-consumer-simple
    networks:
      - spring-boot-kafka-quickstarts
    depends_on:
      - kafka-producer-simple
    ports:
      - "8083:8080"
    restart: unless-stopped
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "kafka": {
            "properties": {
              "bootstrap.servers": "broker:29092"
            }
          }
        }

networks:
  spring-boot-kafka-quickstarts:
    driver: bridge
